/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bye: typeof import('./src/components/common-screen/components/Bye.vue')['default']
    CommonCrud: typeof import('./src/components/common-crud/index.vue')['default']
    CommonScreen: typeof import('./src/components/common-screen/index.vue')['default']
    Hello: typeof import('./src/components/common-screen/components/Hello.vue')['default']
    JsonEditor: typeof import('./src/components/json-editor/index.vue')['default']
    Mapbox: typeof import('./src/components/mapbox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsContent: typeof import('radix-vue')['TabsContent']
    TabsList: typeof import('radix-vue')['TabsList']
    TabsRoot: typeof import('radix-vue')['TabsRoot']
    TabsTrigger: typeof import('radix-vue')['TabsTrigger']
  }
}
